class Keys(object):
    name = 'name'
    version = 'version'
    license = 'license'
    licenseType = ':type'
    summary = 'summary'
    homepage = 'homepage'
    authors = 'authors'
    source = 'source'
    iosDeploymentTarget = 'ios.deployment_target'
